name: base
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy=1.23.1
  - pip:
    - albumentations==1.3.0
    - opencv-python==4.6.0.66
    - einops==0.3.0
    - fastapi==0.89.1
    - Pillow==9.4.0
    - timm==0.6.12
    - pydantic==1.10.4
    - requests==2.28.1
    - xformers==0.0.16
    - tqdm==4.64.1
    - pytorch-lightning==1.4.2
    - omegaconf==2.1.1
    - transformers==4.19.2
    - invisible-watermark>=0.1.5
    - torchmetrics==0.6.0
    - open_clip_torch==2.0.2
    - kornia==0.6
    - python-multipart
    - uvicorn[standard]
